In [ ]:
from tensorflow import keras
[name for name in dir(keras.initializers) if not name.startswith("_")]

['Constant',
 'GlorotNormal',
 'GlorotUniform',
 'HeNormal',
 'HeUniform',
 'Identity',
 'Initializer',
 'LecunNormal',
 'LecunUniform',
 'Ones',
 'Orthogonal',
 'RandomNormal',
 'RandomUniform',
 'TruncatedNormal',
 'VarianceScaling',
 'Zeros',
 'constant',
 'deserialize',
 'get',
 'glorot_normal',
 'glorot_uniform',
 'he_normal',
 'he_uniform',
 'identity',
 'lecun_normal',
 'lecun_uniform',
 'ones',
 'orthogonal',
 'random_normal',
 'random_uniform',
 'serialize',
 'truncated_normal',
 'variance_scaling',
 'zeros']

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Create a simple model with a dense layer
model = Sequential([
    Dense(10, activation="relu", kernel_initializer="ones", input_shape=(2,2))
])

# Compile the model (optional for visualization)
model.compile(optimizer="adam", loss="mean_squared_error")

# Access the weights of the dense layer
dense_layer_weights = model.layers[0].get_weights()[0]
bias_values = model.layers[0].get_weights()[1]

# Print the weight values
print("Weight values:")
print(dense_layer_weights)

# Print the bias values
print("Bias values:")
print(bias_values)


Weight values:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Bias values:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
